.PHONY: echo1 echo2 echo3

echo1:
	go run echo1/main.go a b c d e f g

echo2:
	go run echo2/main.go a b c d e f g

echo3:
	go run echo3/main.go a b c d e f g

.PHONY: dup1 dup2 dup3

dup1:
	go run dup1/main.go

dup2:
	go run dup2/main.go

dup3:
	go run dup3/main.go dup3/test.txt

.PHONY: e1.1 e1.2 e1.3 e1.4

e1.1:
	go run exercise/1.1/main.go a b c d e f g

e1.2:
	go run exercise/1.2/main.go a b c d e f g

e1.3:
	go run exercise/1.3/main.go a b c d e f g

e1.4:
	go run exercise/1.4/main.go exercise/1.4/test.txt exercise/1.4/test2.txt